{
 "title": "Pipeline Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Completions by Phase & Status",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " sum(brimble_pipeline_duration_seconds_count) by (phase, status)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Pipeline Success Ratio by Phase",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 9, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(brimble_pipeline_duration_seconds_count{status=\"success\"}) by (phase)\r\n/ sum(brimble_pipeline_duration_seconds_count) by (phase)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Build Phase Error Count",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "brimble_pipeline_errors_total{phase=\"build\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Phase Duration (p95, p50, p99)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(brimble_pipeline_duration_seconds_bucket[10m])) by (le, phase))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(brimble_pipeline_duration_seconds_bucket[10m])) by (le, phase))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(brimble_pipeline_duration_seconds_bucket[10m])) by (le, phase))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Phase Duration (p95, p50, p99)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(brimble_pipeline_duration_seconds_bucket[10m])) by (le, phase))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(brimble_pipeline_duration_seconds_bucket[10m])) by (le, phase))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(brimble_pipeline_duration_seconds_bucket[10m])) by (le, phase))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pipeline Errors by Phase",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(brimble_pipeline_errors_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Clone Phase Average Duration",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(brimble_pipeline_duration_seconds_sum{phase=\"clone\"}[10m])\r\n/ rate(brimble_pipeline_duration_seconds_count{phase=\"clone\"}[10m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}