{
 "title": "Logs Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Pipeline Runner Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{service=\"brimble-api\", event=\"pipeline_runner_failed\"}"
    }
   ]
  },
  {
   "title": "Pipeline Completed Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{service=\"brimble-api\", event=\"pipeline_runner_completed\"}"
    }
   ]
  },
  {
   "title": "HTTP Errors",
   "type": "logs",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{service=\"brimble-api\", level=\"error\", event=\"http_request\"}"
    }
   ]
  },
  {
   "title": "Slow Request",
   "type": "logs",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 8 },
   "targets": [
    {
     "expr": "{service=\"brimble-api\", event=\"http_request\"} | json | durationSeconds > 1"
    }
   ]
  },
  {
   "title": "Deployment Domain ",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{service=\"brimble-api\", domain=\"deployment\"}"
    }
   ]
  },
  {
   "title": "DeadLetter Domain ",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "{service=\"brimble-api\", domain=\"dead-letter\"}"
    }
   ]
  },
  {
   "title": "All Errors   ",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "{service=\"brimble-api\", level=\"error\"}"
    }
   ]
  }
 ]
}