{
 "title": "Request Error Duration",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Requests by Status Code",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(brimble_http_requests_total) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Brible Request Rate By route",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(brimble_http_requests_total[5m])) by (route)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Brible Average Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(brimble_http_request_duration_seconds_sum[5m])\r\n/ rate(brimble_http_request_duration_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Brible Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(brimble_http_requests_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate %",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(brimble_http_errors_total[1m]) / rate(brimble_http_requests_total[1m]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency By Route (P50, P90, P95,)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, rate(brimble_http_request_duration_seconds_bucket[5m]))",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "histogram_quantile(0.90, rate(brimble_http_request_duration_seconds_bucket[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, rate(brimble_http_request_duration_seconds_bucket[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(brimble_http_request_duration_seconds_bucket[5m])) by (le, route))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}